spring:
  application:
    name: user-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
    name: user-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

server:
  port: 8081

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      operationsSorter: "method"
      tagsSorted: "alpha"

application:
  description: @project.description@
  version: @project.version@