spring:
  application:
    name: email-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: email-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.miniedu.model.kafka.events"
        spring.json.use.type.headers: true

server:
  port: 8082

logging:
  level:
    org.apache.kafka: DEBUG
    org.springframework.kafka: DEBUG